use_frameworks!

platform :ios, '8.0'

target 'ComponentC_Example' do
  pod 'ComponentC', :path => '../'

  target 'ComponentC_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
